"use client";
import {ReactNode,useEffect,useRef,useState} from "react";
import {Columns2,Maximize2,GripVertical} from "lucide-react";
export default function ResizableSplit({left,right}: {left:ReactNode;right:ReactNode}) {
  const ref=useRef<HTMLDivElement>(null),[ratio,setRatio]=useState(55),[tab,setTab]=useState("both");
  useEffect(() => {try {const n=Number(localStorage.getItem("cvb:latex-split"));if(n>=25&&n<=75)setRatio(n);}catch{}},[]);
  const update=(value:number) => {const n=Math.max(25,Math.min(75,value));setRatio(n);try{localStorage.setItem("cvb:latex-split",String(n));}catch{}};
  return <><div className="split-controls"><button type="button" aria-pressed={tab==="both"} onClick={()=>setTab("both")}><Columns2 size={16}/>Split view</button><button type="button" aria-pressed={tab==="code"} onClick={()=>setTab("code")}><Maximize2 size={16}/>Code</button><button type="button" aria-pressed={tab==="pdf"} onClick={()=>setTab("pdf")}>PDF</button><label className="split-width-control">Code width <input aria-label="LaTeX code pane width" type="range" min={25} max={75} value={ratio} onChange={e=>update(Number(e.target.value))}/>{Math.round(ratio)}%</label></div><div ref={ref} className={`resizable-split split-${tab}`} style={{gridTemplateColumns:tab==="both"?`minmax(0,${ratio}fr) 14px minmax(0,${100-ratio}fr)`:"minmax(0,1fr)"}}>{tab!=="pdf"&&left}{tab==="both"&&<div className="split-divider" role="separator" aria-label="Resize LaTeX and PDF panes" aria-orientation="vertical" aria-valuenow={Math.round(ratio)} aria-valuemin={25} aria-valuemax={75} tabIndex={0} onDoubleClick={()=>update(55)} onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();update(ratio+(e.key==="ArrowLeft"?-3:3));}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.drag="true";}} onPointerMove={e=>{if(e.currentTarget.dataset.drag!=="true")return;const rect=ref.current?.getBoundingClientRect();if(rect)update((e.clientX-rect.left)/rect.width*100);}} onPointerUp={e=>{delete e.currentTarget.dataset.drag;}} onPointerCancel={e=>{delete e.currentTarget.dataset.drag;}}><GripVertical size={16}/></div>}{tab!=="code"&&right}</div></>;
}
